import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'
import '../style/globals.css'
import { ThemeProvider } from '@mui/material'
import theme from '@/style/theme'
import NavBar from '@/components/NavBar/NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}
interface RootLayoutProps {
    children: React.ReactNode
}

const RootLayout: React.FC<Readonly<RootLayoutProps>> = (props: Readonly<RootLayoutProps>) => {
    return (
        <html lang='en'>
            <AppRouterCacheProvider options={{ enableCssLayer: false }}>
                <ThemeProvider theme={theme}>
                    <body className={inter.className}>
                        <NavBar />
                        <main className='flex min-h-screen flex-col items-center justify-between p-24'>
                            {props.children}
                        </main>
                    </body>
                </ThemeProvider>
            </AppRouterCacheProvider>
        </html>
    )
}

export default RootLayout
